on: [deployment_status, workflow_dispatch]

jobs:
  update-docsearch:
    name: Update DocSearch
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
                  -e APPLICATION_ID=$APPLICATION_ID \
                  -e API_KEY=$API_KEY \
                  -e "CONFIG=$(cat ./algolia.config.json | jq -r tostring)" \
                  algolia/docsearch-scraper 
